name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-22.04
    outputs:
      branch: ${{ steps.determine_branch.outputs.branch }}
      repo: ${{ steps.downcase_repo.outputs.repo }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine branch
        id: determine_branch
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
          else
            echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: downcase REPO
        id: downcase_repo
        run: |
          echo "repo=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: free disk space
        run: |
          docker system prune --volumes -af            

  build_gnu_debug:
    runs-on: ubuntu-22.04
    needs: setup
    env:
      BRANCH: ${{ needs.setup.outputs.branch }}
      REPO: ${{ needs.setup.outputs.repo }}
    steps:
      - name: Build Docker image with debug PETSc
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: false
          file: ./dockerfiles/Dockerfile
          build-args: |
            BRANCH=${{ env.BRANCH }}
            ARCH=arch-linux-c-debug
            OPT=-O0 -g

  build_gnu_opt:
    runs-on: ubuntu-22.04
    needs: setup
    env:
      BRANCH: ${{ needs.setup.outputs.branch }}
      REPO: ${{ needs.setup.outputs.repo }}    
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}      
      - name: Build Docker image for pull requests
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          file: ./dockerfiles/Dockerfile
          tags: ${{ env.REPO }}:latest
          build-args: |
            BRANCH=${{ env.BRANCH }}
            ARCH=arch-linux-c-opt

  build_gnu_opt_64_bit:
    runs-on: ubuntu-22.04
    needs: setup
    env:
      BRANCH: ${{ needs.setup.outputs.branch }}
      REPO: ${{ needs.setup.outputs.repo }}    
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}        
      - name: Build Docker image for pull requests with 64-bit PETSc
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          file: ./dockerfiles/Dockerfile_64_bit
          tags: ${{ env.REPO }}_64_bit:latest
          build-args: |
            BRANCH=${{ env.BRANCH }}
            ARCH=arch-linux-c-opt

  build_nvidia_opt:
    runs-on: ubuntu-22.04
    needs: setup
    env:
      BRANCH: ${{ needs.setup.outputs.branch }}
      REPO: ${{ needs.setup.outputs.repo }}
    steps:
      - name: Build Docker image with PETSc and NVIDIA compilers
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: false
          file: ./dockerfiles/Dockerfile_nvidia
          build-args: |
            BRANCH=${{ env.BRANCH }}
            ARCH=arch-linux-nvidia            