name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine branch to build
        id: branch
        run: |
          # For pull requests, use the head ref (the branch that triggered the PR)
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
          else
            # For push events, use the ref name
            echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV} 

      - name: Build Docker image with debug PETSc
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: false
          file: ./dockerfiles/Dockerfile
          build-args: |
            BRANCH=${{ env.BRANCH }}    
            ARCH=arch-linux-c-debug

      - name: free disk space
        run: |
          docker system prune --volumes -af  

      - name: Build Docker image with PETSc and NVIDIA compilers
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: false
          file: ./dockerfiles/Dockerfile_nvidia
          build-args: |
            BRANCH=${{ env.BRANCH }}   
            ARCH=arch-linux-nvidia

      - name: free disk space
        run: |
          docker system prune --volumes -af   

      - name: Build and push Docker image for push events
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          file: ./dockerfiles/Dockerfile
          tags: ${{ env.REPO }}:latest
          build-args: |
            BRANCH=${{ env.BRANCH }}
            ARCH=arch-linux-c-opt

      - name: Build Docker image for pull requests
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: false
          file: ./dockerfiles/Dockerfile
          tags: ${{ env.REPO }}:pr-build
          build-args: |
            BRANCH=${{ env.BRANCH }}
            ARCH=arch-linux-c-opt

      - name: Build and push 64-bit Docker image for push events
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          file: ./dockerfiles/Dockerfile_64_bit
          tags: ${{ env.REPO }}_64_bit:latest
          build-args: |
            BRANCH=${{ env.BRANCH }}
            ARCH=arch-linux-c-opt

      - name: Build 64-bit Docker image for pull requests
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: false
          file: ./dockerfiles/Dockerfile_64_bit
          tags: ${{ env.REPO }}_64_bit:pr-build
          build-args: |
            BRANCH=${{ env.BRANCH }}
            ARCH=arch-linux-c-opt